---
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --time={resources.time}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}
    --output=logs/{rule}/{rule}-%j.out
    --parsable
    # --gres={resources.gres}         # enable for GPU
cluster-status:
  status-sacct-robust.sh
default-resources:
  - partition=physical
  - mem_mb=4000
  - time=5
  - proj=punim1712
  # - gres=''         # enable for GPU
restart-times: 0
max-jobs-per-second: 50
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
jobs: 128
keep-going: true
rerun-incomplete: true
printshellcmds: true
use-singularity: true
singularity-args: "-B $PWD,$TMPDIR \
                   --nv \
                   -H $(mktemp -d) \
                   --pwd $PWD \
                   --containall --cleanenv --writable-tmpfs"
